### ISSUE TITLE
[Question] How does the '.EventName' function resolve namespace?

### ISSUE THREAD

**Issue by hussainabeer** [manchenkoff/nuxt-laravel-echo#8]
Hi, apologies in advance for the extremely long issue lol.
I am curious about how this is working. 

```js
const stockUpdateEvent = ".StockUpdated";
function subscribeToStockUpdates() {
  echo
    .private(stockUpdateChannel)
    .listen(stockUpdateEvent, (e) => handleStockUpdate(e))
    .error((error) => console.error(error));
}
```

This is working perfectly fine. But according to the [docs on laravel](https://laravel.com/docs/11.x/broadcasting#namespaces), it says:
```js
// Alternatively, you may prefix event classes with a . when subscribing to them using Echo. This will allow you to always specify the fully-qualified class name:

Echo.channel('orders')
    .listen('.Namespace\\Event\\Class', (e) => {
        // ...
    });
```

And the [source](https://github.com/laravel/echo/blob/50b03a8fb0afae7b6ad271d7e3209f1ddb71901e/src/util/event-formatter.ts#L15) of the echo project shows the below code

```js
function format(event) {
    // If event starts with '.' or '\', remove the first character
    if (['.', '\\'].includes(event.charAt(0))) {
        return event.substring(1);
    } 
    // If namespace exists, prepend namespace followed by a dot
    else if (this.namespace) {
        event = this.namespace + '.' + event;
    }
    // Replace all '.' with '\' in the final event string and return
    return event.replace(/\./g, '\\');
}
```

It doesnt work unless i put a dot infront of the name. But from what I see on the source of echo, as above, if there is a dot as the first character of the name:
It simply removes the dot and returns the name (which according to the docs would be a fully qualified class name like `App\Events\EventName` )

So, my question is, how is it not causing issues when I put a `.` infront of the event name string, but instead causes issues when I dont put one.

**Comment by manchenkoff** [comment]
Hey @hussainabeer, I'm unfamiliar with the `echo` source code, maybe in your case you end up in the second case with `namespace.eventName`. I never tried to use event names without a dot since everywhere I noticed the same approach as [here](https://github.com/laravel/echo/blob/50b03a8fb0afae7b6ad271d7e3209f1ddb71901e/src/channel/channel.ts#L26) 😄
